/**
 * @module
 *
 * Trellis server-side authentication library for session-key based authentication.
 *
 * - Session keys are Ed25519 keys represented as base64url (32-byte raw public key).
 * - Proofs are Ed25519 signatures over SHA-256(buildProofInput(...)).
 * - Services load their session key seed from `TRELLIS_SESSION_KEY_SEED`.
 */

export {
  type AuthActivateDeviceInput,
  type AuthActivateDeviceOutput,
  type AuthGetDeviceActivationStatusInput,
  type AuthGetDeviceActivationStatusOutput,
  type AuthListDeviceActivationsInput,
  type AuthListDeviceActivationsOutput,
  type AuthRevokeDeviceActivationInput,
  type AuthRevokeDeviceActivationResponse,
  buildDeviceActivationPayload,
  buildDeviceActivationUrl,
  buildDeviceWaitProofInput,
  createDeviceActivationClient,
  createDeviceNatsAuthToken,
  deriveDeviceConfirmationCode,
  deriveDeviceIdentity,
  deriveDeviceQrMac,
  type DeviceActivationPayload,
  type DeviceActivationTransport,
  type DeviceActivationWaitRequest,
  type DeviceIdentity,
  encodeDeviceActivationPayload,
  getDeviceConnectInfo,
  type GetDeviceConnectInfoInput,
  type GetDeviceConnectInfoOutput,
  parseDeviceActivationPayload,
  signDeviceWaitRequest,
  verifyDeviceConfirmationCode,
  verifyDeviceWaitSignature,
  waitForDeviceActivation,
  type WaitForDeviceActivationResponse,
} from "./device_activation.ts";
export {
  type AuthConfig,
  bindFlow,
  bindSession,
  buildLoginUrl,
  clearSessionKey,
  createRpcProof,
  fetchPortalFlowState,
  generateSessionKey,
  getOrCreateSessionKey,
  getPublicSessionKey,
  hasSessionKey,
  isBindSuccessResponse,
  loadSessionKey,
  natsConnectSigForBindingToken,
  portalFlowIdFromUrl,
  portalProviderLoginUrl,
  portalRedirectLocation,
  type SessionKeyHandle,
  signBytes,
  submitPortalApproval,
} from "./browser.ts";
export {
  buildProofInput,
  createProof,
  type ProofParams,
  verifyProof,
} from "./proof.ts";
export {
  ApprovalRecordViewSchema,
  AuthActivateDeviceResponseSchema,
  AuthActivateDeviceSchema,
  AuthClearDevicePortalSelectionResponseSchema,
  AuthClearDevicePortalSelectionSchema,
  AuthClearLoginPortalSelectionResponseSchema,
  AuthClearLoginPortalSelectionSchema,
  AuthCreateDeviceProfileResponseSchema,
  AuthCreateDeviceProfileSchema,
  AuthCreatePortalResponseSchema,
  AuthCreatePortalSchema,
  AuthDecideDeviceActivationReviewResponseSchema,
  AuthDecideDeviceActivationReviewSchema,
  AuthDeviceActivationReviewRequestedEventSchema,
  AuthDisableDeviceInstanceResponseSchema,
  AuthDisableDeviceInstanceSchema,
  AuthDisableDeviceProfileResponseSchema,
  AuthDisableDeviceProfileSchema,
  AuthDisableInstanceGrantPolicyResponseSchema,
  AuthDisableInstanceGrantPolicySchema,
  AuthDisablePortalResponseSchema,
  AuthDisablePortalSchema,
  type AuthenticatedDevice,
  AuthenticatedDeviceSchema,
  type AuthenticatedService,
  type AuthenticatedUser,
  AuthGetDeviceActivationStatusResponseSchema,
  AuthGetDeviceActivationStatusSchema,
  AuthGetDeviceConnectInfoResponseSchema,
  AuthGetDeviceConnectInfoSchema,
  AuthGetDevicePortalDefaultResponseSchema,
  AuthGetDevicePortalDefaultSchema,
  AuthGetInstalledContractResponseSchema,
  AuthGetInstalledContractSchema,
  AuthGetLoginPortalDefaultResponseSchema,
  AuthGetLoginPortalDefaultSchema,
  AuthInstallServiceResponseSchema,
  AuthInstallServiceSchema,
  AuthListApprovalsResponseSchema,
  AuthListApprovalsSchema,
  AuthListDeviceActivationReviewsResponseSchema,
  AuthListDeviceActivationReviewsSchema,
  AuthListDeviceActivationsResponseSchema,
  AuthListDeviceActivationsSchema,
  AuthListDeviceInstancesResponseSchema,
  AuthListDeviceInstancesSchema,
  AuthListDevicePortalSelectionsResponseSchema,
  AuthListDevicePortalSelectionsSchema,
  AuthListDeviceProfilesResponseSchema,
  AuthListDeviceProfilesSchema,
  AuthListInstalledContractsResponseSchema,
  AuthListInstalledContractsSchema,
  AuthListInstanceGrantPoliciesResponseSchema,
  AuthListInstanceGrantPoliciesSchema,
  AuthListLoginPortalSelectionsResponseSchema,
  AuthListLoginPortalSelectionsSchema,
  AuthListPortalsResponseSchema,
  AuthListPortalsSchema,
  AuthListServicesResponseSchema,
  AuthListServicesSchema,
  AuthListUsersResponseSchema,
  AuthListUsersSchema,
  type AuthMeResponse,
  AuthMeResponseSchema,
  AuthMeSchema,
  AuthProvisionDeviceInstanceResponseSchema,
  AuthProvisionDeviceInstanceSchema,
  AuthRevokeApprovalResponseSchema,
  AuthRevokeApprovalSchema,
  AuthRevokeDeviceActivationResponseSchema,
  AuthRevokeDeviceActivationSchema,
  AuthSetDevicePortalDefaultResponseSchema,
  AuthSetDevicePortalDefaultSchema,
  AuthSetDevicePortalSelectionResponseSchema,
  AuthSetDevicePortalSelectionSchema,
  AuthSetLoginPortalDefaultResponseSchema,
  AuthSetLoginPortalDefaultSchema,
  AuthSetLoginPortalSelectionResponseSchema,
  AuthSetLoginPortalSelectionSchema,
  AuthUpdateUserResponseSchema,
  AuthUpdateUserSchema,
  AuthUpgradeServiceContractResponseSchema,
  AuthUpgradeServiceContractSchema,
  AuthUpsertInstanceGrantPolicyResponseSchema,
  AuthUpsertInstanceGrantPolicySchema,
  AuthValidateRequestResponseSchema,
  AuthValidateRequestSchema,
  CallerViewSchema,
  ContractAnalysisSchema,
  ContractAnalysisSummarySchema,
  type DeviceActivationRecord,
  DeviceActivationRecordSchema,
  DeviceActivationReviewSchema,
  DeviceConnectInfoSchema,
  type DevicePortalDefault,
  DevicePortalDefaultSchema,
  type DevicePortalSelection,
  DevicePortalSelectionSchema,
  DeviceProfileSchema,
  DeviceSchema,
  DigestSchema,
  InstalledContractDetailSchema,
  InstalledContractSchema,
  type InstanceGrantPolicy,
  InstanceGrantPolicySchema,
  LoginPortalDefaultSchema,
  LoginPortalSelectionSchema,
  OpenObjectSchema,
  type PortalFlowApp,
  type PortalFlowApproval,
  type PortalFlowApprovalDeniedState,
  type PortalFlowApprovalRequiredState,
  type PortalFlowChooseProviderState,
  type PortalFlowExpiredState,
  type PortalFlowInsufficientCapabilitiesState,
  type PortalFlowProvider,
  type PortalFlowRedirectState,
  type PortalFlowState,
  PortalFlowStateSchema,
  type PortalFlowUser,
  PortalSchema,
  ServiceViewSchema,
  UserViewSchema,
  WaitForDeviceActivationResponseSchema,
} from "./protocol.ts";
export {
  type ApprovalDecision,
  ApprovalDecisionSchema,
  type BindRequest,
  BindRequestSchema,
  type BindResponse,
  BindResponseSchema,
  type BindSuccessResponse,
  BindSuccessResponseSchema,
  type ClientTransportEndpoints,
  ClientTransportEndpointsSchema,
  type ClientTransports,
  ClientTransportsSchema,
  type ContractApproval,
  ContractApprovalSchema,
  type LoginQuery,
  LoginQuerySchema,
  type NatsAuthTokenV1,
  NatsAuthTokenV1Schema,
  type SentinelCreds,
  SentinelCredsSchema,
} from "./schemas.ts";
export {
  createAuth,
  type NatsConnectOptions,
  type TrellisAuth,
} from "./session_auth.ts";
export { trellisIdFromOriginId } from "./trellis_id.ts";
export {
  base64urlDecode,
  base64urlEncode,
  canonicalizeJsonValue,
  sha256,
  toArrayBuffer,
  utf8,
} from "./utils.ts";
