/**
 * @module
 *
 * Trellis server-side authentication library for session-key based authentication.
 *
 * - Session keys are Ed25519 keys represented as base64url (32-byte raw public key).
 * - Proofs are Ed25519 signatures over SHA-256(buildProofInput(...)).
 * - Services load their session key seed from `TRELLIS_SESSION_KEY_SEED`.
 */

export {
  buildWorkloadActivationPayload,
  buildWorkloadActivationUrl,
  buildWorkloadWaitProofInput,
  createWorkloadNatsAuthToken,
  createWorkloadActivationClient,
  deriveWorkloadConfirmationCode,
  deriveWorkloadIdentity,
  deriveWorkloadQrMac,
  encodeWorkloadActivationPayload,
  getWorkloadConnectInfo,
  parseWorkloadActivationPayload,
  signWorkloadWaitRequest,
  verifyWorkloadConfirmationCode,
  verifyWorkloadWaitSignature,
  waitForWorkloadActivation,
  type AuthActivateWorkloadInput,
  type AuthActivateWorkloadOutput,
  type AuthListWorkloadActivationsInput,
  type AuthListWorkloadActivationsOutput,
  type AuthRevokeWorkloadActivationInput,
  type AuthRevokeWorkloadActivationResponse,
  type GetWorkloadConnectInfoInput,
  type GetWorkloadConnectInfoOutput,
  type WaitForWorkloadActivationResponse,
  type WorkloadActivationPayload,
  type WorkloadActivationTransport,
  type WorkloadActivationWaitRequest,
  type WorkloadIdentity,
} from "./workload_activation.ts";
export {
  type AuthConfig,
  bindFlow,
  bindSession,
  buildLoginUrl,
  clearSessionKey,
  createRpcProof,
  fetchPortalFlowState,
  generateSessionKey,
  getOrCreateSessionKey,
  getPublicSessionKey,
  hasSessionKey,
  isBindSuccessResponse,
  loadSessionKey,
  natsConnectSigForBindingToken,
  portalFlowIdFromUrl,
  portalProviderLoginUrl,
  portalRedirectLocation,
  type SessionKeyHandle,
  signBytes,
  submitPortalApproval,
} from "./browser.ts";
export {
  buildProofInput,
  createProof,
  type ProofParams,
  verifyProof,
} from "./proof.ts";
export {
  ApprovalRecordViewSchema,
  AuthActivateWorkloadResponseSchema,
  AuthActivateWorkloadSchema,
  AuthClearLoginPortalSelectionResponseSchema,
  AuthClearLoginPortalSelectionSchema,
  AuthClearWorkloadPortalSelectionResponseSchema,
  AuthClearWorkloadPortalSelectionSchema,
  AuthCreatePortalResponseSchema,
  AuthCreatePortalSchema,
  AuthCreateWorkloadProfileResponseSchema,
  AuthCreateWorkloadProfileSchema,
  type PortalFlowApp,
  type PortalFlowApproval,
  type PortalFlowApprovalDeniedState,
  type PortalFlowApprovalRequiredState,
  type PortalFlowChooseProviderState,
  type PortalFlowExpiredState,
  type PortalFlowInsufficientCapabilitiesState,
  type PortalFlowProvider,
  type PortalFlowRedirectState,
  type PortalFlowState,
  type PortalFlowUser,
  AuthDisablePortalResponseSchema,
  AuthDisablePortalSchema,
  AuthGetLoginPortalDefaultResponseSchema,
  AuthGetLoginPortalDefaultSchema,
  AuthDisableWorkloadInstanceResponseSchema,
  AuthDisableWorkloadInstanceSchema,
  AuthDisableWorkloadProfileResponseSchema,
  AuthDisableWorkloadProfileSchema,
  AuthGetWorkloadConnectInfoResponseSchema,
  AuthGetWorkloadConnectInfoSchema,
  AuthGetWorkloadPortalDefaultResponseSchema,
  AuthGetWorkloadPortalDefaultSchema,
  AuthListLoginPortalSelectionsResponseSchema,
  AuthListLoginPortalSelectionsSchema,
  AuthListPortalsResponseSchema,
  AuthListPortalsSchema,
   AuthListWorkloadPortalSelectionsResponseSchema,
   AuthListWorkloadPortalSelectionsSchema,
   AuthListWorkloadActivationReviewsResponseSchema,
   AuthListWorkloadActivationReviewsSchema,
   AuthListWorkloadActivationsResponseSchema,
   AuthListWorkloadActivationsSchema,
   AuthGetWorkloadActivationStatusResponseSchema,
   AuthGetWorkloadActivationStatusSchema,
   AuthListWorkloadInstancesResponseSchema,
   AuthListWorkloadInstancesSchema,
   AuthListWorkloadProfilesResponseSchema,
   AuthListWorkloadProfilesSchema,
   AuthProvisionWorkloadInstanceResponseSchema,
   AuthProvisionWorkloadInstanceSchema,
  AuthDecideWorkloadActivationReviewResponseSchema,
  AuthDecideWorkloadActivationReviewSchema,
  AuthWorkloadActivationReviewRequestedEventSchema,
  AuthRevokeWorkloadActivationResponseSchema,
   AuthRevokeWorkloadActivationSchema,
  AuthSetLoginPortalDefaultResponseSchema,
  AuthSetLoginPortalDefaultSchema,
  AuthSetLoginPortalSelectionResponseSchema,
  AuthSetLoginPortalSelectionSchema,
  AuthSetWorkloadPortalDefaultResponseSchema,
  AuthSetWorkloadPortalDefaultSchema,
  AuthSetWorkloadPortalSelectionResponseSchema,
  AuthSetWorkloadPortalSelectionSchema,
  AuthGetInstalledContractResponseSchema,
  AuthGetInstalledContractSchema,
  AuthInstallServiceResponseSchema,
  AuthInstallServiceSchema,
  AuthListApprovalsResponseSchema,
  AuthListApprovalsSchema,
  AuthListInstalledContractsResponseSchema,
  AuthListInstalledContractsSchema,
  AuthListServicesResponseSchema,
  AuthListServicesSchema,
  AuthListUsersResponseSchema,
  AuthListUsersSchema,
  AuthMeResponseSchema,
  AuthMeSchema,
  type AuthMeResponse,
  AuthRevokeApprovalResponseSchema,
  AuthRevokeApprovalSchema,
  AuthUpdateUserResponseSchema,
  AuthUpdateUserSchema,
  AuthUpgradeServiceContractResponseSchema,
  AuthUpgradeServiceContractSchema,
  AuthValidateRequestResponseSchema,
  AuthValidateRequestSchema,
  type AuthenticatedService,
  type AuthenticatedUser,
  type AuthenticatedWorkload,
  AuthenticatedWorkloadSchema,
  CallerViewSchema,
  ContractAnalysisSchema,
  ContractAnalysisSummarySchema,
  DigestSchema,
  InstalledContractDetailSchema,
  InstalledContractSchema,
  LoginPortalDefaultSchema,
  LoginPortalSelectionSchema,
  OpenObjectSchema,
  PortalSchema,
  PortalFlowStateSchema,
  ServiceViewSchema,
  UserViewSchema,
   WaitForWorkloadActivationResponseSchema,
  WorkloadActivationReviewSchema,
  WorkloadPortalDefaultSchema,
  WorkloadPortalSelectionSchema,
  WorkloadActivationRecordSchema,
  type WorkloadActivationRecord,
  WorkloadConnectInfoSchema,
  WorkloadProfileSchema,
  WorkloadSchema,
} from "./protocol.ts";
export {
  type ApprovalDecision,
  ApprovalDecisionSchema,
  type BindRequest,
  BindRequestSchema,
  type BindResponse,
  BindResponseSchema,
  type BindSuccessResponse,
  BindSuccessResponseSchema,
  type ContractApproval,
  ContractApprovalSchema,
  type LoginQuery,
  LoginQuerySchema,
  type NatsAuthTokenV1,
  NatsAuthTokenV1Schema,
  type SentinelCreds,
  SentinelCredsSchema,
} from "./schemas.ts";
export {
  createAuth,
  type NatsConnectOptions,
  type TrellisAuth,
} from "./session_auth.ts";
export { trellisIdFromOriginId } from "./trellis_id.ts";
export {
  base64urlDecode,
  base64urlEncode,
  canonicalizeJsonValue,
  sha256,
  toArrayBuffer,
  utf8,
} from "./utils.ts";
