<script lang="ts">
  import { browser } from "$app/environment";
  import { onMount } from "svelte";
  import PortalBrand from "$lib/components/PortalBrand.svelte";
  import { trellisUrl } from "$lib/config";
  import {
    accountFlowIdFromUrl,
    accountFlowProviderLoginUrl,
    completeAccountFlowLocalPassword,
    defaultProfileValue,
    flowKindLabel,
    hasLocalProvider,
    isExpectedInviteFlow,
    loadAccountFlowState,
    parseAccountFlowOAuthCompletion,
    unavailableProviders,
    type AccountFlowState,
    type LocalPasswordSuccess,
  } from "./page_state";

  let flowId = $state<string | null>(null);
  let flowState = $state.raw<AccountFlowState | null>(null);
  let loading = $state(true);
  let submitting = $state(false);
  let error = $state<string | null>(null);
  let completion = $state<LocalPasswordSuccess | null>(null);
  let username = $state("");
  let password = $state("");
  let name = $state("");
  let email = $state("");
  let defaultsApplied = false;

  const active = $derived(flowState?.status === "active" ? flowState : null);
  const canSubmit = $derived(
    Boolean(active && flowId && hasLocalProvider(active) && username.trim() && password && !submitting && !completion),
  );

  function currentFlowId(): string | null {
    if (!browser) return null;
    return accountFlowIdFromUrl(new URL(window.location.href));
  }

  function currentOAuthCompletion(): LocalPasswordSuccess | null {
    if (!browser) return null;
    const completionState = parseAccountFlowOAuthCompletion(new URL(window.location.href));
    return completionState ? { status: "created", userId: completionState.userId } : null;
  }

  function applyDefaults(): void {
    if (!active || defaultsApplied) return;
    name = defaultProfileValue(active, "name");
    email = defaultProfileValue(active, "email");
    defaultsApplied = true;
  }

  async function loadFlow(): Promise<void> {
    const oauthCompletion = currentOAuthCompletion();
    if (oauthCompletion) {
      flowId = currentFlowId();
      completion = oauthCompletion;
      loading = false;
      error = null;
      return;
    }

    flowId = currentFlowId();
    if (!flowId) {
      error = "Missing invitation flow id. Open the invitation link generated by Trellis.";
      loading = false;
      return;
    }
    loading = true;
    error = null;
    try {
      flowState = await loadAccountFlowState(trellisUrl, flowId);
      applyDefaults();
    } catch (caught) {
      error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      loading = false;
    }
  }

  async function submitLocal(): Promise<void> {
    if (!flowId || !active) return;
    submitting = true;
    error = null;
    try {
      completion = await completeAccountFlowLocalPassword(trellisUrl, flowId, {
        username: username.trim(),
        password,
        name,
        email,
      });
      password = "";
    } catch (caught) {
      error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      submitting = false;
    }
  }

  onMount(() => {
    if (!browser) return;
    void loadFlow();
  });
</script>

<svelte:head>
  <title>Accept invitation · Trellis</title>
</svelte:head>

{#snippet targetSummary()}
  {#if active?.target}
    <section class="portal-subtle-panel rounded-box p-4 text-sm leading-6">
      <p class="portal-section-label">Target account</p>
      <p class="mt-1 font-semibold text-base-content">{active.target.name ?? active.target.email ?? active.target.userId}</p>
      {#if active.target.email && active.target.email !== active.target.name}
        <p class="portal-copy">{active.target.email}</p>
      {/if}
      <p class="mono mt-1 break-all text-xs text-base-content/45">{active.target.userId}</p>
    </section>
  {/if}
{/snippet}

<div class="portal-shell flex min-h-screen flex-col items-center justify-center gap-7 px-4 py-10 sm:px-6" data-theme="portal">
  <div class="portal-card card w-full max-w-md border border-base-300">
    <div class="card-body gap-6 p-7 sm:p-8">
      <div class="flex justify-center"><PortalBrand subtitle="Account invitation" /></div>

      {#if loading}
        <div class="flex items-center gap-4 py-3" aria-live="polite">
          <span class="loading loading-ring loading-lg" aria-hidden="true"></span>
          <div><p class="text-sm font-medium text-base-content">Loading invitation</p><p class="portal-copy text-xs">Resolving account-flow state.</p></div>
        </div>
      {:else if completion}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Account ready</h1><p class="portal-copy mt-2 text-sm">Your invitation has been accepted and your account is ready.</p></div>
        <div class="portal-subtle-panel rounded-box p-4 text-sm leading-6 text-base-content/70"><p class="portal-section-label">Canonical user</p><p class="mono mt-1 break-all text-base-content">{completion.userId}</p></div>
      {:else if flowState?.status === "expired"}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Invitation expired</h1><p class="portal-copy mt-2 text-sm">This invitation is missing or no longer active. Ask an administrator for a new link.</p></div>
      {:else if flowState?.status === "consumed"}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Invitation already used</h1><p class="portal-copy mt-2 text-sm">This {flowKindLabel(flowState.kind)} request has already been completed.</p></div>
      {:else if active}
        <div><h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Accept your invitation</h1><p class="portal-copy mt-2 text-sm">Create local username and password credentials for this Trellis account.</p></div>
        {@render targetSummary()}
        {#if !isExpectedInviteFlow(active)}
          <div class="alert alert-warning text-sm" role="alert"><span>This link is for {flowKindLabel(active.kind)}, not an invitation. You can continue only if this is the link you intended to use.</span></div>
        {/if}
        {#if hasLocalProvider(active)}
          <form class="grid gap-4" onsubmit={(event) => { event.preventDefault(); void submitLocal(); }}>
            <label class="form-control gap-1.5"><span class="label-text text-sm font-medium text-base-content">Username</span><input class="input input-bordered w-full" autocomplete="username" disabled={submitting} required bind:value={username} /></label>
            <label class="form-control gap-1.5"><span class="label-text text-sm font-medium text-base-content">Password</span><input class="input input-bordered w-full" autocomplete="new-password" disabled={submitting} required type="password" bind:value={password} /></label>
            <label class="form-control gap-1.5"><span class="label-text text-sm font-medium text-base-content">Name <span class="font-normal text-base-content/45">optional</span></span><input class="input input-bordered w-full" autocomplete="name" disabled={submitting} bind:value={name} /></label>
            <label class="form-control gap-1.5"><span class="label-text text-sm font-medium text-base-content">Email <span class="font-normal text-base-content/45">optional</span></span><input class="input input-bordered w-full" autocomplete="email" disabled={submitting} type="email" bind:value={email} /></label>
            <button class="btn btn-primary btn-block" disabled={!canSubmit} type="submit">{#if submitting}<span class="loading loading-spinner loading-sm" aria-hidden="true"></span>Accepting...{:else}Accept invitation{/if}</button>
          </form>
        {:else}
          <div class="alert alert-info text-sm" role="alert"><span>This invitation does not allow username and password setup.</span></div>
        {/if}
        {#each unavailableProviders(active) as provider (provider.id)}
          <a class="btn btn-outline btn-block" href={accountFlowProviderLoginUrl(trellisUrl, active.flowId, provider.id)}>
            Continue with {provider.displayName}
          </a>
        {/each}
      {/if}

      {#if submitting}<p class="portal-copy text-sm" aria-live="polite">Submitting invitation...</p>{/if}
      {#if error}<div class="alert alert-error text-sm" role="alert"><span>{error}</span></div>{/if}
    </div>
  </div>
</div>
