import {
  AuthAccountFlowsCreateIdentityLinkSchema,
  AuthAccountFlowsCreateLocalPasswordFlowSchema,
  AuthAccountFlowsCreateProviderFlowSchema,
  AuthAccountFlowsCreateResponseSchema,
  AuthCapabilitiesListResponseSchema,
  AuthCapabilitiesListSchema,
  AuthCapabilityGroupsDeleteResponseSchema,
  AuthCapabilityGroupsDeleteSchema,
  AuthCapabilityGroupsGetResponseSchema,
  AuthCapabilityGroupsGetSchema,
  AuthCapabilityGroupsListResponseSchema,
  AuthCapabilityGroupsListSchema,
  AuthCapabilityGroupsPutResponseSchema,
  AuthCapabilityGroupsPutSchema,
  AuthIdentitiesListResponseSchema,
  AuthIdentitiesListSchema,
  AuthIdentityEnvelopesRevokeResponseSchema,
  AuthIdentityEnvelopesRevokeSchema,
  AuthRequestsValidateResponseSchema,
  AuthRequestsValidateSchema,
  AuthSessionsMeResponseSchema,
  AuthSessionsMeSchema,
  AuthUserIdentitiesListResponseSchema,
  AuthUserIdentitiesListSchema,
  AuthUserIdentitiesUnlinkResponseSchema,
  AuthUserIdentitiesUnlinkSchema,
  AuthUsersCreateResponseSchema,
  AuthUsersCreateSchema,
  AuthUsersGetResponseSchema,
  AuthUsersGetSchema,
  AuthUsersListResponseSchema,
  AuthUsersListSchema,
  AuthUsersUpdateResponseSchema,
  AuthUsersUpdateSchema,
  PortalFlowStateSchema,
} from "@qlever-llc/trellis/auth";
import {
  AuthDeploymentSchema,
  AuthDeploymentsCreateResponseSchema,
  AuthDeploymentsCreateSchema,
  AuthDeploymentsDisableResponseSchema,
  AuthDeploymentsDisableSchema,
  AuthDeploymentsEnableResponseSchema,
  AuthDeploymentsEnableSchema,
  AuthDeploymentsListResponseSchema,
  AuthDeploymentsListSchema,
  AuthDeploymentsRemoveResponseSchema,
  AuthDeploymentsRemoveSchema,
  AuthDevicesConnectInfoGetResponseSchema,
  AuthDevicesConnectInfoGetSchema,
  AuthDevicesDisableResponseSchema,
  AuthDevicesDisableSchema,
  AuthDevicesEnableResponseSchema,
  AuthDevicesEnableSchema,
  AuthDevicesListResponseSchema,
  AuthDevicesListSchema,
  AuthDevicesProvisionResponseSchema,
  AuthDevicesProvisionSchema,
  AuthDevicesRemoveResponseSchema,
  AuthDevicesRemoveSchema,
  AuthDeviceUserAuthoritiesApprovedEventSchema,
  AuthDeviceUserAuthoritiesListResponseSchema,
  AuthDeviceUserAuthoritiesListSchema,
  AuthDeviceUserAuthoritiesRequestedEventSchema,
  AuthDeviceUserAuthoritiesResolvedEventSchema,
  AuthDeviceUserAuthoritiesReviewRequestedEventSchema,
  AuthDeviceUserAuthoritiesReviewsDecideResponseSchema,
  AuthDeviceUserAuthoritiesReviewsDecideSchema,
  AuthDeviceUserAuthoritiesReviewsListResponseSchema,
  AuthDeviceUserAuthoritiesReviewsListSchema,
  AuthDeviceUserAuthoritiesRevokeResponseSchema,
  AuthDeviceUserAuthoritiesRevokeSchema,
  AuthEnvelopeExpansionsListResponseSchema,
  AuthEnvelopeExpansionsListSchema,
  AuthEnvelopeExpansionsRejectResponseSchema,
  AuthEnvelopeExpansionsRejectSchema,
  AuthEnvelopesApproveRequestResponseSchema,
  AuthEnvelopesApproveRequestSchema,
  AuthEnvelopesChangesPreviewResponseSchema,
  AuthEnvelopesChangesPreviewSchema,
  AuthEnvelopesExpandResponseSchema,
  AuthEnvelopesExpandSchema,
  AuthEnvelopesGetResponseSchema,
  AuthEnvelopesGetSchema,
  AuthEnvelopesGrantOverridesPutSchema,
  AuthEnvelopesGrantOverridesRemoveSchema,
  AuthEnvelopesGrantOverridesResponseSchema,
  AuthEnvelopesListResponseSchema,
  AuthEnvelopesListSchema,
  AuthEnvelopesShrinkResponseSchema,
  AuthEnvelopesShrinkSchema,
  AuthIdentitiesGrantsListResponseSchema,
  AuthIdentitiesGrantsListSchema,
  AuthPortalsGetResponseSchema,
  AuthPortalsGetSchema,
  AuthPortalsListResponseSchema,
  AuthPortalsListSchema,
  AuthPortalsLoginSettingsGetSchema,
  AuthPortalsLoginSettingsResponseSchema,
  AuthPortalsLoginSettingsUpdateSchema,
  AuthPortalsPutResponseSchema,
  AuthPortalsPutSchema,
  AuthPortalsRemoveResponseSchema,
  AuthPortalsRemoveSchema,
  AuthPortalsRoutesPutResponseSchema,
  AuthPortalsRoutesPutSchema,
  AuthPortalsRoutesRemoveResponseSchema,
  AuthPortalsRoutesRemoveSchema,
  AuthResolveDeviceUserAuthoritiesProgressSchema,
  AuthResolveDeviceUserAuthoritiesResponseSchema,
  AuthResolveDeviceUserAuthoritiesSchema,
  AuthServiceInstancesDisableResponseSchema,
  AuthServiceInstancesDisableSchema,
  AuthServiceInstancesEnableResponseSchema,
  AuthServiceInstancesEnableSchema,
  AuthServiceInstancesListResponseSchema,
  AuthServiceInstancesListSchema,
  AuthServiceInstancesProvisionResponseSchema,
  AuthServiceInstancesProvisionSchema,
  AuthServiceInstancesRemoveResponseSchema,
  AuthServiceInstancesRemoveSchema,
  DeploymentContractEvidenceSchema,
  DeploymentEnvelopeSchema,
  DeploymentGrantOverrideSchema,
  DeploymentPortalRouteSchema,
  DeploymentResourceBindingSchema,
  DeviceActivationRecordSchema,
  DeviceActivationReviewSchema,
  DeviceConnectInfoSchema,
  DeviceDeploymentSchema,
  DeviceSchema,
  EnvelopeBoundarySchema,
  EnvelopeExpansionRequestSchema,
  ServiceDeploymentSchema,
  ServiceInstanceSchema,
} from "../../../packages/trellis/auth/protocol.ts";
import { defineServiceContract } from "@qlever-llc/trellis/contracts";
import {
  HealthResponseSchema,
  HealthRpcSchema,
} from "@qlever-llc/trellis/health";
import {
  type AuthConnectionsOpenedEvent,
  AuthConnectionsOpenedEventSchema,
} from "../../../packages/trellis/models/auth/events/AuthConnect.ts";
import {
  type AuthConnectionsKickedEvent,
  AuthConnectionsKickedEventSchema,
} from "../../../packages/trellis/models/auth/events/AuthConnectionKicked.ts";
import {
  type AuthConnectionsClosedEvent,
  AuthConnectionsClosedEventSchema,
} from "../../../packages/trellis/models/auth/events/AuthDisconnect.ts";
import {
  type AuthSessionsRevokedEvent,
  AuthSessionsRevokedEventSchema,
} from "../../../packages/trellis/models/auth/events/AuthSessionRevoked.ts";
import {
  AuthConnectionsKickResponseSchema,
  AuthConnectionsKickSchema,
} from "../../../packages/trellis/models/auth/rpc/KickConnection.ts";
import {
  AuthConnectionsListResponseSchema,
  AuthConnectionsListSchema,
} from "../../../packages/trellis/models/auth/rpc/ListConnections.ts";
import {
  AuthSessionsListResponseSchema,
  AuthSessionsListSchema,
} from "../../../packages/trellis/models/auth/rpc/ListSessions.ts";
import {
  AuthSessionsLogoutResponseSchema,
  AuthSessionsLogoutSchema,
} from "../../../packages/trellis/models/auth/rpc/Logout.ts";
import {
  AuthSessionsRevokeResponseSchema,
  AuthSessionsRevokeSchema,
} from "../../../packages/trellis/models/auth/rpc/RevokeSession.ts";

const schemas = {
  AuthDeviceUserAuthoritiesReviewsDecideRequest:
    AuthDeviceUserAuthoritiesReviewsDecideSchema,
  AuthDeviceUserAuthoritiesReviewsDecideResponse:
    AuthDeviceUserAuthoritiesReviewsDecideResponseSchema,
  AuthDeviceUserAuthoritiesReviewsListRequest:
    AuthDeviceUserAuthoritiesReviewsListSchema,
  AuthDeviceUserAuthoritiesReviewsListResponse:
    AuthDeviceUserAuthoritiesReviewsListResponseSchema,
  AuthDevicesProvisionRequest: AuthDevicesProvisionSchema,
  AuthDevicesProvisionResponse: AuthDevicesProvisionResponseSchema,
  AuthDevicesListRequest: AuthDevicesListSchema,
  AuthDevicesListResponse: AuthDevicesListResponseSchema,
  AuthDevicesDisableRequest: AuthDevicesDisableSchema,
  AuthDevicesDisableResponse: AuthDevicesDisableResponseSchema,
  AuthResolveDeviceUserAuthoritiesRequest:
    AuthResolveDeviceUserAuthoritiesSchema,
  AuthResolveDeviceUserAuthoritiesProgress:
    AuthResolveDeviceUserAuthoritiesProgressSchema,
  AuthResolveDeviceUserAuthoritiesResponse:
    AuthResolveDeviceUserAuthoritiesResponseSchema,
  AuthDevicesConnectInfoGetRequest: AuthDevicesConnectInfoGetSchema,
  AuthDevicesConnectInfoGetResponse: AuthDevicesConnectInfoGetResponseSchema,
  AuthDeviceUserAuthoritiesListRequest: AuthDeviceUserAuthoritiesListSchema,
  AuthDeviceUserAuthoritiesListResponse:
    AuthDeviceUserAuthoritiesListResponseSchema,
  AuthDeviceUserAuthoritiesRevokeRequest: AuthDeviceUserAuthoritiesRevokeSchema,
  AuthDeviceUserAuthoritiesRevokeResponse:
    AuthDeviceUserAuthoritiesRevokeResponseSchema,
  PortalFlowState: PortalFlowStateSchema,
  Device: DeviceSchema,
  DeviceDeployment: DeviceDeploymentSchema,
  ServiceDeployment: ServiceDeploymentSchema,
  AuthDeployment: AuthDeploymentSchema,
  ServiceInstance: ServiceInstanceSchema,
  EnvelopeBoundary: EnvelopeBoundarySchema,
  DeploymentEnvelope: DeploymentEnvelopeSchema,
  DeploymentResourceBinding: DeploymentResourceBindingSchema,
  DeploymentContractEvidence: DeploymentContractEvidenceSchema,
  DeploymentPortalRoute: DeploymentPortalRouteSchema,
  DeploymentGrantOverride: DeploymentGrantOverrideSchema,
  EnvelopeExpansionRequest: EnvelopeExpansionRequestSchema,
  DeviceActivationReview: DeviceActivationReviewSchema,
  DeviceActivationRecord: DeviceActivationRecordSchema,
  DeviceConnectInfo: DeviceConnectInfoSchema,
  AuthDeviceUserAuthoritiesReviewRequestedEvent:
    AuthDeviceUserAuthoritiesReviewRequestedEventSchema,
  AuthDeviceUserAuthoritiesRequestedEvent:
    AuthDeviceUserAuthoritiesRequestedEventSchema,
  AuthDeviceUserAuthoritiesApprovedEvent:
    AuthDeviceUserAuthoritiesApprovedEventSchema,
  AuthDeviceUserAuthoritiesResolvedEvent:
    AuthDeviceUserAuthoritiesResolvedEventSchema,
  AuthDeploymentsCreateRequest: AuthDeploymentsCreateSchema,
  AuthDeploymentsCreateResponse: AuthDeploymentsCreateResponseSchema,
  AuthDeploymentsListRequest: AuthDeploymentsListSchema,
  AuthDeploymentsListResponse: AuthDeploymentsListResponseSchema,
  AuthEnvelopesListRequest: AuthEnvelopesListSchema,
  AuthEnvelopesListResponse: AuthEnvelopesListResponseSchema,
  AuthEnvelopesGetRequest: AuthEnvelopesGetSchema,
  AuthEnvelopesGetResponse: AuthEnvelopesGetResponseSchema,
  AuthEnvelopesGrantOverridesPutRequest: AuthEnvelopesGrantOverridesPutSchema,
  AuthEnvelopesGrantOverridesResponse:
    AuthEnvelopesGrantOverridesResponseSchema,
  AuthEnvelopesGrantOverridesRemoveRequest:
    AuthEnvelopesGrantOverridesRemoveSchema,
  AuthEnvelopesExpandRequest: AuthEnvelopesExpandSchema,
  AuthEnvelopesExpandResponse: AuthEnvelopesExpandResponseSchema,
  AuthEnvelopesApproveRequestRequest: AuthEnvelopesApproveRequestSchema,
  AuthEnvelopesApproveRequestResponse:
    AuthEnvelopesApproveRequestResponseSchema,
  AuthEnvelopeExpansionsListRequest: AuthEnvelopeExpansionsListSchema,
  AuthEnvelopeExpansionsListResponse: AuthEnvelopeExpansionsListResponseSchema,
  AuthEnvelopeExpansionsRejectRequest: AuthEnvelopeExpansionsRejectSchema,
  AuthEnvelopeExpansionsRejectResponse:
    AuthEnvelopeExpansionsRejectResponseSchema,
  AuthEnvelopesChangesPreviewRequest: AuthEnvelopesChangesPreviewSchema,
  AuthEnvelopesChangesPreviewResponse:
    AuthEnvelopesChangesPreviewResponseSchema,
  AuthEnvelopesShrinkRequest: AuthEnvelopesShrinkSchema,
  AuthEnvelopesShrinkResponse: AuthEnvelopesShrinkResponseSchema,
  AuthDeploymentsDisableRequest: AuthDeploymentsDisableSchema,
  AuthDeploymentsDisableResponse: AuthDeploymentsDisableResponseSchema,
  AuthDeploymentsEnableRequest: AuthDeploymentsEnableSchema,
  AuthDeploymentsEnableResponse: AuthDeploymentsEnableResponseSchema,
  AuthDeploymentsRemoveRequest: AuthDeploymentsRemoveSchema,
  AuthDeploymentsRemoveResponse: AuthDeploymentsRemoveResponseSchema,
  AuthServiceInstancesProvisionRequest: AuthServiceInstancesProvisionSchema,
  AuthServiceInstancesProvisionResponse:
    AuthServiceInstancesProvisionResponseSchema,
  AuthServiceInstancesListRequest: AuthServiceInstancesListSchema,
  AuthServiceInstancesListResponse: AuthServiceInstancesListResponseSchema,
  AuthServiceInstancesDisableRequest: AuthServiceInstancesDisableSchema,
  AuthServiceInstancesDisableResponse:
    AuthServiceInstancesDisableResponseSchema,
  AuthServiceInstancesEnableRequest: AuthServiceInstancesEnableSchema,
  AuthServiceInstancesEnableResponse: AuthServiceInstancesEnableResponseSchema,
  AuthServiceInstancesRemoveRequest: AuthServiceInstancesRemoveSchema,
  AuthServiceInstancesRemoveResponse: AuthServiceInstancesRemoveResponseSchema,
  AuthIdentitiesListRequest: AuthIdentitiesListSchema,
  AuthIdentitiesListResponse: AuthIdentitiesListResponseSchema,
  AuthCapabilitiesListRequest: AuthCapabilitiesListSchema,
  AuthCapabilitiesListResponse: AuthCapabilitiesListResponseSchema,
  AuthCapabilityGroupsListRequest: AuthCapabilityGroupsListSchema,
  AuthCapabilityGroupsListResponse: AuthCapabilityGroupsListResponseSchema,
  AuthCapabilityGroupsGetRequest: AuthCapabilityGroupsGetSchema,
  AuthCapabilityGroupsGetResponse: AuthCapabilityGroupsGetResponseSchema,
  AuthCapabilityGroupsPutRequest: AuthCapabilityGroupsPutSchema,
  AuthCapabilityGroupsPutResponse: AuthCapabilityGroupsPutResponseSchema,
  AuthCapabilityGroupsDeleteRequest: AuthCapabilityGroupsDeleteSchema,
  AuthCapabilityGroupsDeleteResponse: AuthCapabilityGroupsDeleteResponseSchema,
  AuthAccountFlowsCreateProviderFlowRequest:
    AuthAccountFlowsCreateProviderFlowSchema,
  AuthAccountFlowsCreateIdentityLinkRequest:
    AuthAccountFlowsCreateIdentityLinkSchema,
  AuthAccountFlowsCreateLocalPasswordFlowRequest:
    AuthAccountFlowsCreateLocalPasswordFlowSchema,
  AuthAccountFlowsCreateResponse: AuthAccountFlowsCreateResponseSchema,
  AuthUsersListRequest: AuthUsersListSchema,
  AuthUsersListResponse: AuthUsersListResponseSchema,
  AuthUsersGetRequest: AuthUsersGetSchema,
  AuthUsersGetResponse: AuthUsersGetResponseSchema,
  AuthUsersCreateRequest: AuthUsersCreateSchema,
  AuthUsersCreateResponse: AuthUsersCreateResponseSchema,
  AuthUserIdentitiesListRequest: AuthUserIdentitiesListSchema,
  AuthUserIdentitiesListResponse: AuthUserIdentitiesListResponseSchema,
  AuthUserIdentitiesUnlinkRequest: AuthUserIdentitiesUnlinkSchema,
  AuthUserIdentitiesUnlinkResponse: AuthUserIdentitiesUnlinkResponseSchema,
  AuthSessionsMeRequest: AuthSessionsMeSchema,
  AuthSessionsMeResponse: AuthSessionsMeResponseSchema,
  AuthIdentityEnvelopesRevokeRequest: AuthIdentityEnvelopesRevokeSchema,
  AuthIdentityEnvelopesRevokeResponse:
    AuthIdentityEnvelopesRevokeResponseSchema,
  AuthUsersUpdateRequest: AuthUsersUpdateSchema,
  AuthUsersUpdateResponse: AuthUsersUpdateResponseSchema,
  AuthPortalsListRequest: AuthPortalsListSchema,
  AuthPortalsListResponse: AuthPortalsListResponseSchema,
  AuthPortalsGetRequest: AuthPortalsGetSchema,
  AuthPortalsGetResponse: AuthPortalsGetResponseSchema,
  AuthPortalsPutRequest: AuthPortalsPutSchema,
  AuthPortalsPutResponse: AuthPortalsPutResponseSchema,
  AuthPortalsRemoveRequest: AuthPortalsRemoveSchema,
  AuthPortalsRemoveResponse: AuthPortalsRemoveResponseSchema,
  AuthPortalsLoginSettingsGetRequest: AuthPortalsLoginSettingsGetSchema,
  AuthPortalsLoginSettingsResponse: AuthPortalsLoginSettingsResponseSchema,
  AuthPortalsLoginSettingsUpdateRequest: AuthPortalsLoginSettingsUpdateSchema,
  AuthPortalsRoutesPutRequest: AuthPortalsRoutesPutSchema,
  AuthPortalsRoutesPutResponse: AuthPortalsRoutesPutResponseSchema,
  AuthPortalsRoutesRemoveRequest: AuthPortalsRoutesRemoveSchema,
  AuthPortalsRoutesRemoveResponse: AuthPortalsRoutesRemoveResponseSchema,
  AuthDevicesEnableRequest: AuthDevicesEnableSchema,
  AuthDevicesEnableResponse: AuthDevicesEnableResponseSchema,
  AuthDevicesRemoveRequest: AuthDevicesRemoveSchema,
  AuthDevicesRemoveResponse: AuthDevicesRemoveResponseSchema,
  AuthRequestsValidateRequest: AuthRequestsValidateSchema,
  AuthRequestsValidateResponse: AuthRequestsValidateResponseSchema,
  HealthRequest: HealthRpcSchema,
  HealthResponse: HealthResponseSchema,
  AuthConnectionsOpenedEvent: AuthConnectionsOpenedEventSchema,
  AuthConnectionsKickedEvent: AuthConnectionsKickedEventSchema,
  AuthConnectionsClosedEvent: AuthConnectionsClosedEventSchema,
  AuthSessionsRevokedEvent: AuthSessionsRevokedEventSchema,
  AuthConnectionsKickRequest: AuthConnectionsKickSchema,
  AuthConnectionsKickResponse: AuthConnectionsKickResponseSchema,
  AuthConnectionsListRequest: AuthConnectionsListSchema,
  AuthConnectionsListResponse: AuthConnectionsListResponseSchema,
  AuthSessionsListRequest: AuthSessionsListSchema,
  AuthSessionsListResponse: AuthSessionsListResponseSchema,
  AuthIdentitiesGrantsListRequest: AuthIdentitiesGrantsListSchema,
  AuthIdentitiesGrantsListResponse: AuthIdentitiesGrantsListResponseSchema,
  AuthSessionsLogoutRequest: AuthSessionsLogoutSchema,
  AuthSessionsLogoutResponse: AuthSessionsLogoutResponseSchema,
  AuthSessionsRevokeRequest: AuthSessionsRevokeSchema,
  AuthSessionsRevokeResponse: AuthSessionsRevokeResponseSchema,
} as const;

function schemaRef<const TName extends keyof typeof schemas & string>(
  schema: TName,
) {
  return { schema } as const;
}

export const TRELLIS_AUTH_RPC = {
  "Auth.Health": {
    version: "v1",
    input: schemaRef("HealthRequest"),
    output: schemaRef("HealthResponse"),
    capabilities: { call: [] },
    errors: ["UnexpectedError"],
  },
  "Auth.Connections.Kick": {
    version: "v1",
    input: schemaRef("AuthConnectionsKickRequest"),
    output: schemaRef("AuthConnectionsKickResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Connections.List": {
    version: "v1",
    input: schemaRef("AuthConnectionsListRequest"),
    output: schemaRef("AuthConnectionsListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Sessions.List": {
    version: "v1",
    input: schemaRef("AuthSessionsListRequest"),
    output: schemaRef("AuthSessionsListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Sessions.Logout": {
    version: "v1",
    input: schemaRef("AuthSessionsLogoutRequest"),
    output: schemaRef("AuthSessionsLogoutResponse"),
    capabilities: { call: [] },
    errors: ["AuthError", "UnexpectedError"],
  },
  "Auth.Sessions.Me": {
    version: "v1",
    input: schemaRef("AuthSessionsMeRequest"),
    output: schemaRef("AuthSessionsMeResponse"),
    capabilities: { call: [] },
    errors: ["AuthError", "UnexpectedError"],
  },
  "Auth.Identities.Grants.List": {
    version: "v1",
    input: schemaRef("AuthIdentitiesGrantsListRequest"),
    output: schemaRef("AuthIdentitiesGrantsListResponse"),
    capabilities: { call: [] },
    errors: ["AuthError", "UnexpectedError"],
  },
  "Auth.Sessions.Revoke": {
    version: "v1",
    input: schemaRef("AuthSessionsRevokeRequest"),
    output: schemaRef("AuthSessionsRevokeResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Requests.Validate": {
    version: "v1",
    input: schemaRef("AuthRequestsValidateRequest"),
    output: schemaRef("AuthRequestsValidateResponse"),
    capabilities: { call: ["service"] },
    authRequired: false,
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Deployments.Create": {
    version: "v1",
    input: schemaRef("AuthDeploymentsCreateRequest"),
    output: schemaRef("AuthDeploymentsCreateResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Deployments.List": {
    version: "v1",
    input: schemaRef("AuthDeploymentsListRequest"),
    output: schemaRef("AuthDeploymentsListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Envelopes.List": {
    version: "v1",
    input: schemaRef("AuthEnvelopesListRequest"),
    output: schemaRef("AuthEnvelopesListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Envelopes.Get": {
    version: "v1",
    input: schemaRef("AuthEnvelopesGetRequest"),
    output: schemaRef("AuthEnvelopesGetResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Envelopes.GrantOverrides.Put": {
    version: "v1",
    input: schemaRef("AuthEnvelopesGrantOverridesPutRequest"),
    output: schemaRef("AuthEnvelopesGrantOverridesResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Envelopes.GrantOverrides.Remove": {
    version: "v1",
    input: schemaRef("AuthEnvelopesGrantOverridesRemoveRequest"),
    output: schemaRef("AuthEnvelopesGrantOverridesResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Envelopes.Expand": {
    version: "v1",
    input: schemaRef("AuthEnvelopesExpandRequest"),
    output: schemaRef("AuthEnvelopesExpandResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.EnvelopeExpansions.Approve": {
    version: "v1",
    input: schemaRef("AuthEnvelopesApproveRequestRequest"),
    output: schemaRef("AuthEnvelopesApproveRequestResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.EnvelopeExpansions.List": {
    version: "v1",
    input: schemaRef("AuthEnvelopeExpansionsListRequest"),
    output: schemaRef("AuthEnvelopeExpansionsListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.EnvelopeExpansions.Reject": {
    version: "v1",
    input: schemaRef("AuthEnvelopeExpansionsRejectRequest"),
    output: schemaRef("AuthEnvelopeExpansionsRejectResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Envelopes.Changes.Preview": {
    version: "v1",
    input: schemaRef("AuthEnvelopesChangesPreviewRequest"),
    output: schemaRef("AuthEnvelopesChangesPreviewResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Envelopes.Shrink": {
    version: "v1",
    input: schemaRef("AuthEnvelopesShrinkRequest"),
    output: schemaRef("AuthEnvelopesShrinkResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Deployments.Disable": {
    version: "v1",
    input: schemaRef("AuthDeploymentsDisableRequest"),
    output: schemaRef("AuthDeploymentsDisableResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Deployments.Enable": {
    version: "v1",
    input: schemaRef("AuthDeploymentsEnableRequest"),
    output: schemaRef("AuthDeploymentsEnableResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Deployments.Remove": {
    version: "v1",
    input: schemaRef("AuthDeploymentsRemoveRequest"),
    output: schemaRef("AuthDeploymentsRemoveResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.ServiceInstances.Provision": {
    version: "v1",
    input: schemaRef("AuthServiceInstancesProvisionRequest"),
    output: schemaRef("AuthServiceInstancesProvisionResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.ServiceInstances.List": {
    version: "v1",
    input: schemaRef("AuthServiceInstancesListRequest"),
    output: schemaRef("AuthServiceInstancesListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.ServiceInstances.Disable": {
    version: "v1",
    input: schemaRef("AuthServiceInstancesDisableRequest"),
    output: schemaRef("AuthServiceInstancesDisableResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.ServiceInstances.Enable": {
    version: "v1",
    input: schemaRef("AuthServiceInstancesEnableRequest"),
    output: schemaRef("AuthServiceInstancesEnableResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.ServiceInstances.Remove": {
    version: "v1",
    input: schemaRef("AuthServiceInstancesRemoveRequest"),
    output: schemaRef("AuthServiceInstancesRemoveResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Identities.List": {
    version: "v1",
    input: schemaRef("AuthIdentitiesListRequest"),
    output: schemaRef("AuthIdentitiesListResponse"),
    capabilities: { call: [] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.IdentityEnvelopes.Revoke": {
    version: "v1",
    input: schemaRef("AuthIdentityEnvelopesRevokeRequest"),
    output: schemaRef("AuthIdentityEnvelopesRevokeResponse"),
    capabilities: { call: [] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.DeviceUserAuthorities.List": {
    version: "v1",
    input: schemaRef("AuthDeviceUserAuthoritiesListRequest"),
    output: schemaRef("AuthDeviceUserAuthoritiesListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Devices.Provision": {
    version: "v1",
    input: schemaRef("AuthDevicesProvisionRequest"),
    output: schemaRef("AuthDevicesProvisionResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Devices.List": {
    version: "v1",
    input: schemaRef("AuthDevicesListRequest"),
    output: schemaRef("AuthDevicesListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Devices.Disable": {
    version: "v1",
    input: schemaRef("AuthDevicesDisableRequest"),
    output: schemaRef("AuthDevicesDisableResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Devices.Enable": {
    version: "v1",
    input: schemaRef("AuthDevicesEnableRequest"),
    output: schemaRef("AuthDevicesEnableResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Devices.Remove": {
    version: "v1",
    input: schemaRef("AuthDevicesRemoveRequest"),
    output: schemaRef("AuthDevicesRemoveResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Devices.ConnectInfo.Get": {
    version: "v1",
    input: schemaRef("AuthDevicesConnectInfoGetRequest"),
    output: schemaRef("AuthDevicesConnectInfoGetResponse"),
    capabilities: { call: [] },
    authRequired: false,
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.DeviceUserAuthorities.Revoke": {
    version: "v1",
    input: schemaRef("AuthDeviceUserAuthoritiesRevokeRequest"),
    output: schemaRef("AuthDeviceUserAuthoritiesRevokeResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.DeviceUserAuthorities.Reviews.List": {
    version: "v1",
    input: schemaRef("AuthDeviceUserAuthoritiesReviewsListRequest"),
    output: schemaRef("AuthDeviceUserAuthoritiesReviewsListResponse"),
    capabilities: { call: ["device.review"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.DeviceUserAuthorities.Reviews.Decide": {
    version: "v1",
    input: schemaRef("AuthDeviceUserAuthoritiesReviewsDecideRequest"),
    output: schemaRef("AuthDeviceUserAuthoritiesReviewsDecideResponse"),
    capabilities: { call: ["device.review"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Users.List": {
    version: "v1",
    input: schemaRef("AuthUsersListRequest"),
    output: schemaRef("AuthUsersListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Users.Get": {
    version: "v1",
    input: schemaRef("AuthUsersGetRequest"),
    output: schemaRef("AuthUsersGetResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Users.Create": {
    version: "v1",
    input: schemaRef("AuthUsersCreateRequest"),
    output: schemaRef("AuthUsersCreateResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.AccountFlows.CreateInvite": {
    version: "v1",
    input: schemaRef("AuthAccountFlowsCreateProviderFlowRequest"),
    output: schemaRef("AuthAccountFlowsCreateResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.AccountFlows.CreateIdentityLink": {
    version: "v1",
    input: schemaRef("AuthAccountFlowsCreateIdentityLinkRequest"),
    output: schemaRef("AuthAccountFlowsCreateResponse"),
    capabilities: { call: [] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.AccountFlows.CreatePasswordSetup": {
    version: "v1",
    input: schemaRef("AuthAccountFlowsCreateLocalPasswordFlowRequest"),
    output: schemaRef("AuthAccountFlowsCreateResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.AccountFlows.CreatePasswordReset": {
    version: "v1",
    input: schemaRef("AuthAccountFlowsCreateLocalPasswordFlowRequest"),
    output: schemaRef("AuthAccountFlowsCreateResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Capabilities.List": {
    version: "v1",
    input: schemaRef("AuthCapabilitiesListRequest"),
    output: schemaRef("AuthCapabilitiesListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.CapabilityGroups.List": {
    version: "v1",
    input: schemaRef("AuthCapabilityGroupsListRequest"),
    output: schemaRef("AuthCapabilityGroupsListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.CapabilityGroups.Get": {
    version: "v1",
    input: schemaRef("AuthCapabilityGroupsGetRequest"),
    output: schemaRef("AuthCapabilityGroupsGetResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.CapabilityGroups.Put": {
    version: "v1",
    input: schemaRef("AuthCapabilityGroupsPutRequest"),
    output: schemaRef("AuthCapabilityGroupsPutResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.CapabilityGroups.Delete": {
    version: "v1",
    input: schemaRef("AuthCapabilityGroupsDeleteRequest"),
    output: schemaRef("AuthCapabilityGroupsDeleteResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Users.Update": {
    version: "v1",
    input: schemaRef("AuthUsersUpdateRequest"),
    output: schemaRef("AuthUsersUpdateResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.UserIdentities.List": {
    version: "v1",
    input: schemaRef("AuthUserIdentitiesListRequest"),
    output: schemaRef("AuthUserIdentitiesListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.UserIdentities.Unlink": {
    version: "v1",
    input: schemaRef("AuthUserIdentitiesUnlinkRequest"),
    output: schemaRef("AuthUserIdentitiesUnlinkResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Portals.List": {
    version: "v1",
    input: schemaRef("AuthPortalsListRequest"),
    output: schemaRef("AuthPortalsListResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "UnexpectedError"],
  },
  "Auth.Portals.Get": {
    version: "v1",
    input: schemaRef("AuthPortalsGetRequest"),
    output: schemaRef("AuthPortalsGetResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Portals.Put": {
    version: "v1",
    input: schemaRef("AuthPortalsPutRequest"),
    output: schemaRef("AuthPortalsPutResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Portals.Remove": {
    version: "v1",
    input: schemaRef("AuthPortalsRemoveRequest"),
    output: schemaRef("AuthPortalsRemoveResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Portals.LoginSettings.Get": {
    version: "v1",
    input: schemaRef("AuthPortalsLoginSettingsGetRequest"),
    output: schemaRef("AuthPortalsLoginSettingsResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Portals.LoginSettings.Update": {
    version: "v1",
    input: schemaRef("AuthPortalsLoginSettingsUpdateRequest"),
    output: schemaRef("AuthPortalsLoginSettingsResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Portals.Routes.Put": {
    version: "v1",
    input: schemaRef("AuthPortalsRoutesPutRequest"),
    output: schemaRef("AuthPortalsRoutesPutResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
  "Auth.Portals.Routes.Remove": {
    version: "v1",
    input: schemaRef("AuthPortalsRoutesRemoveRequest"),
    output: schemaRef("AuthPortalsRoutesRemoveResponse"),
    capabilities: { call: ["admin"] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
} as const;

export const TRELLIS_AUTH_OPERATIONS = {
  "Auth.DeviceUserAuthorities.Resolve": {
    version: "v1",
    input: schemaRef("AuthResolveDeviceUserAuthoritiesRequest"),
    progress: schemaRef("AuthResolveDeviceUserAuthoritiesProgress"),
    output: schemaRef("AuthResolveDeviceUserAuthoritiesResponse"),
    capabilities: { call: [] },
    errors: ["AuthError", "ValidationError", "UnexpectedError"],
  },
} as const;

export const TRELLIS_AUTH_EVENTS = {
  "Auth.Connections.Opened": {
    version: "v1",
    event: schemaRef("AuthConnectionsOpenedEvent"),
    capabilities: {
      publish: ["events.auth"],
      subscribe: ["events.auth"],
    },
  },
  "Auth.Connections.Kicked": {
    version: "v1",
    event: schemaRef("AuthConnectionsKickedEvent"),
    capabilities: {
      publish: ["events.auth"],
      subscribe: ["events.auth"],
    },
  },
  "Auth.Connections.Closed": {
    version: "v1",
    event: schemaRef("AuthConnectionsClosedEvent"),
    capabilities: {
      publish: ["events.auth"],
      subscribe: ["events.auth"],
    },
  },
  "Auth.Sessions.Revoked": {
    version: "v1",
    event: schemaRef("AuthSessionsRevokedEvent"),
    capabilities: {
      publish: ["events.auth"],
      subscribe: ["events.auth"],
    },
  },
  "Auth.DeviceUserAuthorities.ReviewRequested": {
    version: "v1",
    event: schemaRef("AuthDeviceUserAuthoritiesReviewRequestedEvent"),
    params: ["/deploymentId"],
    capabilities: {
      publish: ["events.auth"],
      subscribe: ["device.review"],
    },
  },
  "Auth.DeviceUserAuthorities.Requested": {
    version: "v1",
    event: schemaRef("AuthDeviceUserAuthoritiesRequestedEvent"),
    params: ["/deploymentId"],
    capabilities: {
      publish: ["events.auth"],
      subscribe: ["device.review"],
    },
  },
  "Auth.DeviceUserAuthorities.Approved": {
    version: "v1",
    event: schemaRef("AuthDeviceUserAuthoritiesApprovedEvent"),
    params: ["/deploymentId"],
    capabilities: {
      publish: ["events.auth"],
      subscribe: ["device.review"],
    },
  },
  "Auth.DeviceUserAuthorities.Resolved": {
    version: "v1",
    event: schemaRef("AuthDeviceUserAuthoritiesResolvedEvent"),
    params: ["/deploymentId"],
    capabilities: {
      publish: ["events.auth"],
      subscribe: ["events.auth", "device.review"],
    },
  },
} as const;

const baseTrellisAuth = defineServiceContract(
  { schemas },
  () => ({
    id: "trellis.auth@v1",
    displayName: "Trellis Auth",
    description:
      "Provide Trellis authentication, session, deployment, instance, and admin RPCs.",
    capabilities: {
      "device.review": {
        displayName: "Review device activation",
        description: "Review and decide pending device activation requests.",
      },
      "events.auth": {
        displayName: "Observe auth events",
        description: "Publish or subscribe to Trellis auth lifecycle events.",
      },
    },
    rpc: TRELLIS_AUTH_RPC,
    operations: TRELLIS_AUTH_OPERATIONS,
    events: TRELLIS_AUTH_EVENTS,
  }),
);

export const trellisAuth = baseTrellisAuth;

export const { CONTRACT_ID, CONTRACT, CONTRACT_DIGEST, API, use } = trellisAuth;
export type Api = typeof API;
export default trellisAuth;
