FROM --platform=$BUILDPLATFORM docker.io/denoland/deno:2.7.7 AS build

WORKDIR /app

COPY js /app/js
COPY generated/js /app/generated/js

WORKDIR /app/js/apps/console

RUN deno run -A npm:vite build

FROM docker.io/library/nginx:1.29-alpine

COPY js/apps/console/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/js/apps/console/docker-entrypoint.d/40-runtime-config.sh /docker-entrypoint.d/40-runtime-config.sh
COPY --from=build /app/js/apps/console/build /usr/share/nginx/html

RUN chmod +x /docker-entrypoint.d/40-runtime-config.sh

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
