/**
 * @module
 *
 * Trellis server-side authentication library for session-key based authentication.
 *
 * - Session keys are Ed25519 keys represented as base64url (32-byte raw public key).
 * - Proofs are Ed25519 signatures over SHA-256(buildProofInput(...)).
 * - Services load their session key seed from `TRELLIS_SESSION_KEY_SEED`.
 */

export {
  type AuthDeviceUserAuthoritiesListInput,
  type AuthDeviceUserAuthoritiesListOutput,
  type AuthDeviceUserAuthoritiesRevokeInput,
  type AuthDeviceUserAuthoritiesRevokeResponse,
  type AuthResolveDeviceUserAuthoritiesInput,
  type AuthResolveDeviceUserAuthoritiesOperation,
  type AuthResolveDeviceUserAuthoritiesOutput,
  type AuthResolveDeviceUserAuthoritiesProgress,
  buildDeviceActivationPayload,
  buildDeviceWaitProofInput,
  createDeviceActivationClient,
  createDeviceNatsAuthToken,
  deriveDeviceConfirmationCode,
  deriveDeviceIdentity,
  deriveDeviceQrMac,
  type DeviceActivationPayload,
  type DeviceActivationTransport,
  type DeviceActivationWaitRequest,
  type DeviceIdentity,
  encodeDeviceActivationPayload,
  getDeviceConnectInfo,
  type GetDeviceConnectInfoInput,
  type GetDeviceConnectInfoOutput,
  parseDeviceActivationPayload,
  signDeviceWaitRequest,
  startDeviceActivationRequest,
  verifyDeviceConfirmationCode,
  verifyDeviceWaitSignature,
  waitForDeviceActivation,
  type WaitForDeviceActivationResponse,
} from "./device_activation.ts";
export {
  type AuthConfig,
  bindFlow,
  buildLoginUrl,
  clearSessionKey,
  createRpcProof,
  fetchPortalFlowState,
  generateSessionKey,
  getOrCreateSessionKey,
  getPublicSessionKey,
  hasSessionKey,
  isBindSuccessResponse,
  loadSessionKey,
  natsConnectSigForIat,
  portalFlowIdFromUrl,
  portalProviderLoginUrl,
  portalRedirectLocation,
  type SessionKeyHandle,
  type SessionKeyOptions,
  type SessionKeyPersistenceMode,
  signBytes,
  startAuthRequest,
  submitPortalApproval,
} from "./browser.ts";
export {
  buildProofInput,
  createProof,
  type ProofParams,
  verifyProof,
} from "./proof.ts";
export {
  ApprovalRecordViewSchema,
  AuthCapabilitiesListResponseSchema,
  AuthCapabilitiesListSchema,
  AuthCapabilityGroupsDeleteResponseSchema,
  AuthCapabilityGroupsDeleteSchema,
  AuthCapabilityGroupsGetResponseSchema,
  AuthCapabilityGroupsGetSchema,
  AuthCapabilityGroupsListResponseSchema,
  AuthCapabilityGroupsListSchema,
  AuthCapabilityGroupsPutResponseSchema,
  AuthCapabilityGroupsPutSchema,
  type AuthDeployment,
  type AuthDeploymentKind,
  AuthDeploymentKindSchema,
  AuthDeploymentSchema,
  AuthDeploymentsCreateResponseSchema,
  AuthDeploymentsCreateSchema,
  AuthDeploymentsDisableResponseSchema,
  AuthDeploymentsDisableSchema,
  AuthDeploymentsEnableResponseSchema,
  AuthDeploymentsEnableSchema,
  AuthDeploymentsListResponseSchema,
  AuthDeploymentsListSchema,
  AuthDeploymentsRemoveResponseSchema,
  AuthDeploymentsRemoveSchema,
  AuthDevicesConnectInfoGetResponseSchema,
  AuthDevicesConnectInfoGetSchema,
  AuthDevicesDisableResponseSchema,
  AuthDevicesDisableSchema,
  AuthDevicesEnableResponseSchema,
  AuthDevicesEnableSchema,
  AuthDevicesListResponseSchema,
  AuthDevicesListSchema,
  AuthDevicesProvisionResponseSchema,
  AuthDevicesProvisionSchema,
  AuthDevicesRemoveResponseSchema,
  AuthDevicesRemoveSchema,
  AuthDeviceUserAuthoritiesApprovedEventSchema,
  AuthDeviceUserAuthoritiesListResponseSchema,
  AuthDeviceUserAuthoritiesListSchema,
  AuthDeviceUserAuthoritiesRequestedEventSchema,
  AuthDeviceUserAuthoritiesResolvedEventSchema,
  AuthDeviceUserAuthoritiesReviewRequestedEventSchema,
  AuthDeviceUserAuthoritiesReviewsDecideResponseSchema,
  AuthDeviceUserAuthoritiesReviewsDecideSchema,
  AuthDeviceUserAuthoritiesReviewsListResponseSchema,
  AuthDeviceUserAuthoritiesReviewsListSchema,
  AuthDeviceUserAuthoritiesRevokeResponseSchema,
  AuthDeviceUserAuthoritiesRevokeSchema,
  type AuthenticatedDevice,
  AuthenticatedDeviceSchema,
  type AuthenticatedService,
  type AuthenticatedUser,
  type AuthEnvelopeExpansionsListResponse,
  AuthEnvelopeExpansionsListResponseSchema,
  AuthEnvelopeExpansionsListSchema,
  type AuthEnvelopesApproveRequestResponse,
  AuthEnvelopesApproveRequestResponseSchema,
  AuthEnvelopesApproveRequestSchema,
  type AuthEnvelopesExpandResponse,
  AuthEnvelopesExpandResponseSchema,
  AuthEnvelopesExpandSchema,
  type AuthEnvelopesGetResponse,
  AuthEnvelopesGetResponseSchema,
  AuthEnvelopesGetSchema,
  type AuthEnvelopesGrantOverridesListResponse,
  AuthEnvelopesGrantOverridesListResponseSchema,
  AuthEnvelopesGrantOverridesListSchema,
  AuthEnvelopesGrantOverridesPutSchema,
  AuthEnvelopesGrantOverridesRemoveSchema,
  type AuthEnvelopesGrantOverridesResponse,
  AuthEnvelopesGrantOverridesResponseSchema,
  type AuthEnvelopesListResponse,
  AuthEnvelopesListResponseSchema,
  AuthEnvelopesListSchema,
  type AuthEnvelopesShrinkResponse,
  AuthEnvelopesShrinkResponseSchema,
  AuthEnvelopesShrinkSchema,
  AuthIdentitiesGrantsListResponseSchema,
  AuthIdentitiesGrantsListSchema,
  AuthIdentitiesListResponseSchema,
  AuthIdentitiesListSchema,
  AuthIdentityEnvelopesRevokeResponseSchema,
  AuthIdentityEnvelopesRevokeSchema,
  AuthPortalsGetResponseSchema,
  AuthPortalsGetSchema,
  AuthPortalsListResponseSchema,
  AuthPortalsListSchema,
  AuthPortalsLoginSettingsGetSchema,
  AuthPortalsLoginSettingsResponseSchema,
  AuthPortalsLoginSettingsUpdateSchema,
  AuthPortalsRoutesPutResponseSchema,
  AuthPortalsRoutesPutSchema,
  AuthPortalsRoutesRemoveResponseSchema,
  AuthPortalsRoutesRemoveSchema,
  AuthRequestsValidateResponseSchema,
  AuthRequestsValidateSchema,
  AuthResolveDeviceUserAuthoritiesProgressSchema,
  AuthResolveDeviceUserAuthoritiesResponseSchema,
  AuthResolveDeviceUserAuthoritiesSchema,
  AuthServiceInstancesDisableResponseSchema,
  AuthServiceInstancesDisableSchema,
  AuthServiceInstancesEnableResponseSchema,
  AuthServiceInstancesEnableSchema,
  AuthServiceInstancesListResponseSchema,
  AuthServiceInstancesListSchema,
  AuthServiceInstancesProvisionResponseSchema,
  AuthServiceInstancesProvisionSchema,
  AuthServiceInstancesRemoveResponseSchema,
  AuthServiceInstancesRemoveSchema,
  type AuthSessionsMeResponse,
  AuthSessionsMeResponseSchema,
  AuthSessionsMeSchema,
  AuthUserIdentitiesListResponseSchema,
  AuthUserIdentitiesListSchema,
  AuthUserIdentitiesUnlinkResponseSchema,
  AuthUserIdentitiesUnlinkSchema,
  AuthUsersAccountFlowCreateResponseSchema,
  AuthUsersCreateResponseSchema,
  AuthUsersCreateSchema,
  AuthUsersGetResponseSchema,
  AuthUsersGetSchema,
  AuthUsersIdentityLinkCreateSchema,
  AuthUsersListResponseSchema,
  AuthUsersListSchema,
  AuthUsersPasswordChangeResponseSchema,
  AuthUsersPasswordChangeSchema,
  AuthUsersPasswordResetCreateSchema,
  AuthUsersUpdateResponseSchema,
  AuthUsersUpdateSchema,
  CallerViewSchema,
  ContractAnalysisSchema,
  ContractAnalysisSummarySchema,
  type DeploymentEnvelope,
  type DeploymentGrantOverride,
  DeploymentGrantOverrideSchema,
  DeploymentPortalRouteSchema,
  DeploymentResourceBindingSchema,
  type DeviceActivationRecord,
  DeviceActivationRecordSchema,
  DeviceActivationReviewSchema,
  DeviceConnectInfoSchema,
  DeviceDeploymentSchema,
  DeviceSchema,
  DigestSchema,
  type EnvelopeBoundary,
  EnvelopeBoundarySchema,
  EnvelopeExpansionRequestSchema,
  EnvelopeHistoryEntrySchema,
  type FlowRegistrationAvailability,
  FlowRegistrationAvailabilitySchema,
  ImplementationOfferSchema,
  type LoginPortalRecord,
  LoginPortalRecordSchema,
  type LoginPortalRoute,
  LoginPortalRouteSchema,
  type LoginPortalSettings,
  LoginPortalSettingsSchema,
  type LoginPortalSummary,
  LoginPortalSummarySchema,
  OpenObjectSchema,
  type ParticipantKind,
  ParticipantKindSchema,
  type PortalFlowApp,
  type PortalFlowApproval,
  type PortalFlowApprovalDeniedState,
  type PortalFlowApprovalRequiredState,
  type PortalFlowChooseProviderState,
  type PortalFlowExpiredState,
  type PortalFlowInsufficientCapabilitiesState,
  type PortalFlowProvider,
  type PortalFlowRedirectState,
  type PortalFlowState,
  PortalFlowStateSchema,
  type PortalFlowUser,
  ServiceDeploymentSchema,
  ServiceInstanceSchema,
  UserGrantViewSchema,
  UserViewSchema,
  WaitForDeviceActivationRequestSchema,
  WaitForDeviceActivationResponseSchema,
} from "./protocol.ts";
export {
  approvalCapabilityKeys,
  type ApprovalDecision,
  ApprovalDecisionSchema,
  type AuthStartFlowResponse,
  AuthStartFlowResponseSchema,
  type AuthStartRequest,
  AuthStartRequestSchema,
  type AuthStartResponse,
  AuthStartResponseSchema,
  type BindResponse,
  BindResponseSchema,
  type BindSuccessResponse,
  BindSuccessResponseSchema,
  type ClientTransportEndpoints,
  ClientTransportEndpointsSchema,
  type ClientTransports,
  ClientTransportsSchema,
  type ContractApproval,
  type ContractApprovalCapability,
  ContractApprovalSchema,
  type NatsAuthTokenV1,
  NatsAuthTokenV1Schema,
  type SentinelCreds,
  SentinelCredsSchema,
  type UserParticipantKind,
  UserParticipantKindSchema,
} from "./schemas.ts";
export {
  buildNatsConnectSignaturePayload,
  createAuth,
  type NatsConnectOptions,
  type TrellisAuth,
} from "./session_auth.ts";
export { correctedIatSeconds, estimateMidpointClockOffsetMs } from "./time.ts";
export { trellisIdFromOriginId } from "./trellis_id.ts";
export {
  base64urlDecode,
  base64urlEncode,
  canonicalizeJsonValue,
  sha256,
  toArrayBuffer,
  utf8,
} from "./utils.ts";
