/**
 * @module
 *
 * Trellis server-side authentication library for session-key based authentication.
 *
 * - Session keys are Ed25519 keys represented as base64url (32-byte raw public key).
 * - Proofs are Ed25519 signatures over SHA-256(buildProofInput(...)).
 * - Services load their session key seed from `TRELLIS_SESSION_KEY_SEED`.
 */

export {
  type AuthActivateDeviceInput,
  type AuthActivateDeviceOperation,
  type AuthActivateDeviceOutput,
  type AuthActivateDeviceProgress,
  type AuthListDeviceActivationsInput,
  type AuthListDeviceActivationsOutput,
  type AuthRevokeDeviceActivationInput,
  type AuthRevokeDeviceActivationResponse,
  buildDeviceActivationPayload,
  buildDeviceWaitProofInput,
  createDeviceActivationClient,
  createDeviceNatsAuthToken,
  deriveDeviceConfirmationCode,
  deriveDeviceIdentity,
  deriveDeviceQrMac,
  type DeviceActivationPayload,
  type DeviceActivationTransport,
  type DeviceActivationWaitRequest,
  type DeviceIdentity,
  encodeDeviceActivationPayload,
  getDeviceConnectInfo,
  type GetDeviceConnectInfoInput,
  type GetDeviceConnectInfoOutput,
  parseDeviceActivationPayload,
  signDeviceWaitRequest,
  startDeviceActivationRequest,
  verifyDeviceConfirmationCode,
  verifyDeviceWaitSignature,
  waitForDeviceActivation,
  type WaitForDeviceActivationResponse,
} from "./device_activation.ts";
export {
  type AuthConfig,
  bindFlow,
  bindSession,
  buildLoginUrl,
  clearSessionKey,
  createRpcProof,
  fetchPortalFlowState,
  generateSessionKey,
  getOrCreateSessionKey,
  getPublicSessionKey,
  hasSessionKey,
  isBindSuccessResponse,
  loadSessionKey,
  natsConnectSigForIat,
  portalFlowIdFromUrl,
  portalProviderLoginUrl,
  portalRedirectLocation,
  type SessionKeyHandle,
  signBytes,
  startAuthRequest,
  submitPortalApproval,
} from "./browser.ts";
export {
  buildProofInput,
  createProof,
  type ProofParams,
  verifyProof,
} from "./proof.ts";
export {
  ApprovalRecordViewSchema,
  AuthActivateDeviceProgressSchema,
  AuthActivateDeviceResponseSchema,
  AuthActivateDeviceSchema,
  AuthApplyDeviceDeploymentContractResponseSchema,
  AuthApplyDeviceDeploymentContractSchema,
  AuthApplyServiceDeploymentContractResponseSchema,
  AuthApplyServiceDeploymentContractSchema,
  AuthClearDevicePortalSelectionResponseSchema,
  AuthClearDevicePortalSelectionSchema,
  AuthClearLoginPortalSelectionResponseSchema,
  AuthClearLoginPortalSelectionSchema,
  AuthCreateDeviceDeploymentResponseSchema,
  AuthCreateDeviceDeploymentSchema,
  AuthCreatePortalResponseSchema,
  AuthCreatePortalSchema,
  AuthCreateServiceDeploymentResponseSchema,
  AuthCreateServiceDeploymentSchema,
  AuthDecideDeviceActivationReviewResponseSchema,
  AuthDecideDeviceActivationReviewSchema,
  AuthDeviceActivationReviewRequestedEventSchema,
  AuthDisableDeviceDeploymentResponseSchema,
  AuthDisableDeviceDeploymentSchema,
  AuthDisableDeviceInstanceResponseSchema,
  AuthDisableDeviceInstanceSchema,
  AuthDisableInstanceGrantPolicyResponseSchema,
  AuthDisableInstanceGrantPolicySchema,
  AuthDisablePortalProfileResponseSchema,
  AuthDisablePortalProfileSchema,
  AuthDisablePortalResponseSchema,
  AuthDisablePortalSchema,
  AuthDisableServiceDeploymentResponseSchema,
  AuthDisableServiceDeploymentSchema,
  AuthDisableServiceInstanceResponseSchema,
  AuthDisableServiceInstanceSchema,
  AuthEnableDeviceDeploymentResponseSchema,
  AuthEnableDeviceDeploymentSchema,
  AuthEnableDeviceInstanceResponseSchema,
  AuthEnableDeviceInstanceSchema,
  AuthEnableServiceDeploymentResponseSchema,
  AuthEnableServiceDeploymentSchema,
  AuthEnableServiceInstanceResponseSchema,
  AuthEnableServiceInstanceSchema,
  type AuthenticatedDevice,
  AuthenticatedDeviceSchema,
  type AuthenticatedService,
  type AuthenticatedUser,
  AuthGetDeviceConnectInfoResponseSchema,
  AuthGetDeviceConnectInfoSchema,
  AuthGetDevicePortalDefaultResponseSchema,
  AuthGetDevicePortalDefaultSchema,
  AuthGetInstalledContractResponseSchema,
  AuthGetInstalledContractSchema,
  AuthGetLoginPortalDefaultResponseSchema,
  AuthGetLoginPortalDefaultSchema,
  AuthListApprovalsResponseSchema,
  AuthListApprovalsSchema,
  AuthListDeviceActivationReviewsResponseSchema,
  AuthListDeviceActivationReviewsSchema,
  AuthListDeviceActivationsResponseSchema,
  AuthListDeviceActivationsSchema,
  AuthListDeviceDeploymentsResponseSchema,
  AuthListDeviceDeploymentsSchema,
  AuthListDeviceInstancesResponseSchema,
  AuthListDeviceInstancesSchema,
  AuthListDevicePortalSelectionsResponseSchema,
  AuthListDevicePortalSelectionsSchema,
  AuthListInstalledContractsResponseSchema,
  AuthListInstalledContractsSchema,
  AuthListInstanceGrantPoliciesResponseSchema,
  AuthListInstanceGrantPoliciesSchema,
  AuthListLoginPortalSelectionsResponseSchema,
  AuthListLoginPortalSelectionsSchema,
  AuthListPortalProfilesResponseSchema,
  AuthListPortalProfilesSchema,
  AuthListPortalsResponseSchema,
  AuthListPortalsSchema,
  AuthListServiceDeploymentsResponseSchema,
  AuthListServiceDeploymentsSchema,
  AuthListServiceInstancesResponseSchema,
  AuthListServiceInstancesSchema,
  AuthListUserGrantsResponseSchema,
  AuthListUserGrantsSchema,
  AuthListUsersResponseSchema,
  AuthListUsersSchema,
  type AuthMeResponse,
  AuthMeResponseSchema,
  AuthMeSchema,
  AuthProvisionDeviceInstanceResponseSchema,
  AuthProvisionDeviceInstanceSchema,
  AuthProvisionServiceInstanceResponseSchema,
  AuthProvisionServiceInstanceSchema,
  AuthRemoveDeviceDeploymentResponseSchema,
  AuthRemoveDeviceDeploymentSchema,
  AuthRemoveDeviceInstanceResponseSchema,
  AuthRemoveDeviceInstanceSchema,
  AuthRemoveServiceDeploymentResponseSchema,
  AuthRemoveServiceDeploymentSchema,
  AuthRemoveServiceInstanceResponseSchema,
  AuthRemoveServiceInstanceSchema,
  AuthRevokeApprovalResponseSchema,
  AuthRevokeApprovalSchema,
  AuthRevokeDeviceActivationResponseSchema,
  AuthRevokeDeviceActivationSchema,
  AuthRevokeUserGrantResponseSchema,
  AuthRevokeUserGrantSchema,
  AuthSetDevicePortalDefaultResponseSchema,
  AuthSetDevicePortalDefaultSchema,
  AuthSetDevicePortalSelectionResponseSchema,
  AuthSetDevicePortalSelectionSchema,
  AuthSetLoginPortalDefaultResponseSchema,
  AuthSetLoginPortalDefaultSchema,
  AuthSetLoginPortalSelectionResponseSchema,
  AuthSetLoginPortalSelectionSchema,
  AuthSetPortalProfileResponseSchema,
  AuthSetPortalProfileSchema,
  AuthUnapplyDeviceDeploymentContractResponseSchema,
  AuthUnapplyDeviceDeploymentContractSchema,
  AuthUnapplyServiceDeploymentContractResponseSchema,
  AuthUnapplyServiceDeploymentContractSchema,
  AuthUpdateUserResponseSchema,
  AuthUpdateUserSchema,
  AuthUpsertInstanceGrantPolicyResponseSchema,
  AuthUpsertInstanceGrantPolicySchema,
  AuthValidateRequestResponseSchema,
  AuthValidateRequestSchema,
  CallerViewSchema,
  ContractAnalysisSchema,
  ContractAnalysisSummarySchema,
  type DeviceActivationRecord,
  DeviceActivationRecordSchema,
  DeviceActivationReviewSchema,
  DeviceConnectInfoSchema,
  DeviceDeploymentSchema,
  type DevicePortalDefault,
  DevicePortalDefaultSchema,
  type DevicePortalSelection,
  DevicePortalSelectionSchema,
  DeviceSchema,
  DigestSchema,
  InstalledContractDetailSchema,
  InstalledContractSchema,
  type InstanceGrantPolicy,
  InstanceGrantPolicySchema,
  LoginPortalDefaultSchema,
  LoginPortalSelectionSchema,
  OpenObjectSchema,
  type ParticipantKind,
  ParticipantKindSchema,
  type PortalFlowApp,
  type PortalFlowApproval,
  type PortalFlowApprovalDeniedState,
  type PortalFlowApprovalRequiredState,
  type PortalFlowChooseProviderState,
  type PortalFlowExpiredState,
  type PortalFlowInsufficientCapabilitiesState,
  type PortalFlowProvider,
  type PortalFlowRedirectState,
  type PortalFlowState,
  PortalFlowStateSchema,
  type PortalFlowUser,
  type PortalProfile,
  PortalProfileSchema,
  PortalSchema,
  ServiceDeploymentSchema,
  ServiceInstanceSchema,
  UserGrantViewSchema,
  UserViewSchema,
  WaitForDeviceActivationResponseSchema,
} from "./protocol.ts";
export {
  type ApprovalDecision,
  ApprovalDecisionSchema,
  type AuthStartFlowResponse,
  AuthStartFlowResponseSchema,
  type AuthStartRequest,
  AuthStartRequestSchema,
  type AuthStartResponse,
  AuthStartResponseSchema,
  type BindRequest,
  BindRequestSchema,
  type BindResponse,
  BindResponseSchema,
  type BindSuccessResponse,
  BindSuccessResponseSchema,
  type ClientTransportEndpoints,
  ClientTransportEndpointsSchema,
  type ClientTransports,
  ClientTransportsSchema,
  type ContractApproval,
  ContractApprovalSchema,
  type LoginQuery,
  LoginQuerySchema,
  type NatsAuthTokenV1,
  NatsAuthTokenV1Schema,
  type SentinelCreds,
  SentinelCredsSchema,
  type UserParticipantKind,
  UserParticipantKindSchema,
} from "./schemas.ts";
export {
  createAuth,
  type NatsConnectOptions,
  type TrellisAuth,
} from "./session_auth.ts";
export { correctedIatSeconds, estimateMidpointClockOffsetMs } from "./time.ts";
export { trellisIdFromOriginId } from "./trellis_id.ts";
export {
  base64urlDecode,
  base64urlEncode,
  canonicalizeJsonValue,
  sha256,
  toArrayBuffer,
  utf8,
} from "./utils.ts";
