[patch.crates-io]
trellis-client = { path = "/home/abalmos/git/qlever/wt-trellis-jobs/rust/crates/trellis-client" }
trellis-contracts = { path = "/home/abalmos/git/qlever/wt-trellis-jobs/rust/crates/trellis-contracts" }
trellis-server = { path = "/home/abalmos/git/qlever/wt-trellis-jobs/rust/crates/trellis-server" }
